project_manager_task:
  description: >
    Carefully analyze the given project description provided by the user.

    Your task is to break it down into a detailed list of frontend and backend tools, technologies, architecture, and user flows required to build the product.

    Think through the implementation from a developer's point of view and clearly define what’s needed for both frontend and backend engineers to begin work without confusion.

    The current year is {current_year}, so use up-to-date tools and practices.

  expected_output: >
    A detailed outline containing:
    - Recommended frontend stack (with reasons)
    - Recommended backend stack (with reasons)
    - API endpoints or integration needs
    - User flows (step-by-step)
    - Any architectural notes (e.g., microservices, monolith, etc.) - prefer monolith
    - Potential third-party tools/services (if any) - not 100% needed

  agent: project_manager